// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAecawmXCUm-Bzh9V2DcK_MRA_re9FtP2k',
    appId: '1:382606243557:web:66d2b4bbf4c55ea4f1c60c',
    messagingSenderId: '382606243557',
    projectId: 'frontend-f5abf',
    authDomain: 'frontend-f5abf.firebaseapp.com',
    storageBucket: 'frontend-f5abf.firebasestorage.app',
    measurementId: 'G-EF2DLBJBP3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFBq8KaDdoT7RWI1MWL0qBa6U2ueu5VvY',
    appId: '1:382606243557:android:4739645ba6b27aecf1c60c',
    messagingSenderId: '382606243557',
    projectId: 'frontend-f5abf',
    storageBucket: 'frontend-f5abf.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAecawmXCUm-Bzh9V2DcK_MRA_re9FtP2k',
    appId: '1:382606243557:web:85230023b8307614f1c60c',
    messagingSenderId: '382606243557',
    projectId: 'frontend-f5abf',
    authDomain: 'frontend-f5abf.firebaseapp.com',
    storageBucket: 'frontend-f5abf.firebasestorage.app',
    measurementId: 'G-5M1LC6SF3V',
  );
}
